// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetRuleCount():Promise<number>;

export function GetSettings():Promise<main.SettingsView>;

export function GetStatus():Promise<string>;

export function SaveSettings(arg1:string,arg2:number,arg3:string):Promise<string>;

export function StartProxy():Promise<string>;

export function StopProxy():Promise<string>;
