// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRuleCount() {
  return window['go']['main']['App']['GetRuleCount']();
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetStressStatus() {
  return window['go']['main']['App']['GetStressStatus']();
}

export function SaveSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3);
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StartStressTest(arg1) {
  return window['go']['main']['App']['StartStressTest'](arg1);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function StopStressTest() {
  return window['go']['main']['App']['StopStressTest']();
}

export function ToggleRule(arg1, arg2) {
  return window['go']['main']['App']['ToggleRule'](arg1, arg2);
}
