// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRuleCount():Promise<number>;

export function GetStatus():Promise<string>;

export function StartProxy():Promise<string>;

export function StopProxy():Promise<string>;
