// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';

export function CreateRule(arg1:config.CreateRuleRequest):Promise<string>;

export function GetAllSessionStatuses():Promise<Record<string, boolean>>;

export function GetRuleCount():Promise<number>;

export function GetRules():Promise<Array<main.RuleView>>;

export function GetSessionStatus(arg1:string):Promise<boolean>;

export function GetSettings():Promise<main.SettingsView>;

export function GetStressStatus():Promise<boolean>;

export function SaveSettings(arg1:string,arg2:string):Promise<string>;

export function StartSession(arg1:string):Promise<string>;

export function StartStressTest(arg1:main.StressConfig):Promise<string>;

export function StopSession(arg1:string):Promise<string>;

export function StopStressTest():Promise<string>;

export function ToggleRule(arg1:string,arg2:boolean):Promise<string>;
